### ISSUE TITLE
plot.td2pLL_mod not found in plot.td2pLL_mod

### ISSUE THREAD

**Issue by jcduda** [jcduda/td2pLL#2]
Check() gives:
```
  > base::assign(".ptime", proc.time(), pos = "CheckExEnv")
  > ### Name: plot.td2pLL_mod
  > ### Title: Plot interactive td2pLL models
  > ### Aliases: plot.td2pLL_mod
  > 
  > ### ** Examples
  > 
  > data(cytotox)
  > data_subset <- cytotox[cytotox$compound == "ASP", c("expo", "dose", "resp")]
  > colnames(data_subset)[1] <- "time"
  > fit <- fit_td2pLL(data = data_subset)
  > plot(fit)
  > plot.td2pLL_mod(x=NULL, td2pLL_coefs = c(h = 2, delta = 5, gamma = 2, c0=1),
  + dose_lim = c(0, 10), time_lim = c(1, 2), xaxis_scale = "linear", n_grid = 200)
  Error in plot.td2pLL_mod(x = NULL, td2pLL_coefs = c(h = 2, delta = 5,  : 
    could not find function "plot.td2pLL_mod"
  Execution halted
```

It works if instead of `plot.td2pLL_mod` I use `td2pLL:::plot.td2pLL_mod()` but thats so cumbersome.
The function is exported already and in the NAMESPACE, why is it not found?

**Comment by jakob-r** [comment]
I am sure that this will help you: https://stackoverflow.com/questions/18512528/how-to-export-s3-method-so-it-is-available-in-namespace

Also I would recommend to write a non s3 function to deal with this situation:

```
plot.td2pLL_mod(x=NULL, td2pLL_coefs = c(h = 2, delta = 5, gamma = 2, c0=1)
```

So maybe `plot_td2pll(coefs, ...)`. And only use `plot.td2pLL_mod` to plot the object.
I have not looked in detail into your code but maybe it's possible that  `plot.td2pLL_mod` extracts the coefs and calls `plot_td2pll(coefs, ...)` internally?

**Comment by jcduda** [comment]
Thank you! 
I will then use `plot_td2pLL(coefs,...)` for the case where no model fit is provided, but simply a model specified by provided coefficients  shall be plotted to
"see how it looks like for some coefficients".  
If I do not have a model fit (of class `td2pLL_mod`) I think `plot.td2pLL_mod` cannot be called, so I just go with the solution for the separate function, thanks :-)
